version: "3.3"

services:
  frontend:
    container_name: frontend
    restart: always
    build: ./client
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    command: npm start
