version: "3.3"

services:
  frontend:
    container_name: frontend
    build: ./Gui
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 5000:5000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
